config/routes.rb
SeriesMark::Application.routes.draw do

  resources :countries

  get '/series/next' => 'series#next', :as => 'next_series'
  
  resources :series do
    resources :seasons do
	  resources :episodes
	end
  end
  
  
  
  resources :genres #do

  root :to => 'series#index'

end

app/controllers/series_controller.rb
class SeriesController < ApplicationController
  before_action :set_series, only: [:show, :edit, :update, :destroy]

  # GET /series
  # GET /series.json
  def index
    @series = Series.all
  end

  # GET /series/1
  # GET /series/1.json
  def show
  end

  # GET /series/new
  def new
    @series = Series.new
  end

  # GET /series/1/edit
  def edit
  end

  # POST /series
  # POST /series.json
  def create
    @series = Series.new(series_params)

    respond_to do |format|
      if @series.save
        format.html { redirect_to @series, notice: 'Series was successfully created.' }
        format.json { render action: 'show', status: :created, location: @series }
      else
        format.html { render action: 'new' }
        format.json { render json: @series.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /series/1
  # PATCH/PUT /series/1.json
  def update
    respond_to do |format|
      if @series.update(series_params)
        format.html { redirect_to @series, notice: 'Series was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @series.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /series/1
  # DELETE /series/1.json
  def destroy
    @series.destroy
    respond_to do |format|
      format.html { redirect_to series_index_url }
      format.json { head :no_content }
    end
  end
  
  def next
	@series = Series.find(:all, :conditions => { :episodes => { :watched => false } }, :joins => :episodes)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_series
      @series = Series.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def series_params
      params.require(:series).permit(:title, :genre_id, :photo, :nSeasons, :year, :country_id, :favorite)
    end
end

app/helpers/series_helper.rb
module SeriesHelper

  def seriesRow(series)
    html='<div class="seriesDivRow">'
    html << '<div class="seriesDivHeader">'
	html << '<input type="hidden" value="' + series.id.to_s + '" />'
	if series.favorite
		html << '<img src="/img/favorite.png" alt="Uncheck favorite" />' 
	else
		html << '<img src="/img/noFavorite.png" alt="Check favorite" />'
	end
	html << '<h2>' + series.title + '</h2>'
	html << '<span>Pending episodes: ' + series.unseen_episodes.count.to_s + ' / ' + series.episodes.count.to_s + '</span>'
	html << '</div>'
	html << '<div class="seriesDivInfo" style="display:none;">'
	if series.extension
		html << '<img alt="Series image" src="/photo_store/' + series.id.to_s + '.' + series.extension + '" />'
	else
		html << '<img alt="No image" src="/photo_store/0.png" />'
	end
	html << '<div>'
	html << '<h3>' + series.title + '</h3>'
	html << '<h3>' + series.year.to_s + '</h3>' if series.year
	html << '<h3>' + series.country.name + '</h3>' if series.country
	html << '<h3>' + series.genre.title + '</h3>'
	html << '<h3>' + series.seasons.count.to_s + ' seasons</h3>'
	html << '</div>'
	html << '<div class="links">'
	html << '<a class="button" href="' + edit_series_path(series) + '">Edit</a>'
	html << link_to('Destroy', series_path(series), method: :delete, data: { confirm: 'Are you sure?' }, class: 'button')
	html << '</div>'
	html << '</div>'
	html << '</div>'
    return html.html_safe
   end

end

app/views/series/_form.html.erb
<%= form_for(@series, :html => { :multipart => true }) do |f| %>
  <% if @series.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@series.errors.count, "error") %> prohibited this series from being saved:</h2>

      <ul>
      <% @series.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :genre_id %><br>
	<%= f.select :genre_id, Genre.find(:all , :order => "title").collect {|g|
		[g.title, g.id]} %>
  </div>
  <div class="field">
    <%= f.label :year %><br>
    <%= f.text_field :year %>
  </div>
  <div class="field">
    <%= f.label :country_id %><br>
	<%= f.select :country_id, Country.find(:all , :order => "name").collect {|g|
		[g.name, g.id]} %>
  </div>
  <div class="field">
    <%= f.label :favorite %><br>
    <%= f.check_box :favorite %>
  </div>
  <div class="field">
	<%= f.label :photo %><br />
	<%= f.file_field :photo %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/series/edit.html.erb
<h1>Editing series</h1>

<%= render 'form' %>

Seasons
<table>
  <thead>
    <tr>
      <th>Title</th>
	  <th>Episodes</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @series.seasons.each do |season| %>
      <tr>
        <td><%= season.title %></td>
		<td><%= season.episodes.count.to_s %></td>
        <td><%= link_to 'Show', season %></td>
        <td><%= link_to 'Edit', edit_season_path(season) %></td>
        <td><%= link_to 'Destroy', season, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Seasons', series_seasons_path(@series) %> |
<%= link_to 'Back', series_index_path %>

app/views/series/index.html.erb
<h1>Listing series</h1>

<script>
	
	$(document).ready(function(){
		$('.seriesDivInfo').each(function(div, r){
			$(div).hide();
		});
		
		$('.seriesDivHeader').click(function(){
			$(this).siblings('.seriesDivInfo').slideToggle();
		});
		
		
	});
	
</script>

    <% @series.each do |series| %>
	  <%= seriesRow(series) %>
    <% end %>
	
<br>

<%= link_to 'New Series', new_series_path %>

app/views/series/new.html.erb
<h1>New series</h1>

<%= render 'form' %>

<%= link_to 'Back', series_index_path %>

app/views/series/next.html.erb
<h1>Listing series</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Genre</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @series.each do |series| %>
      <tr>
        <td><%= series.title %></td>
        <td><%= series.genre_id %></td>
        <td><%= link_to 'Show', series %></td>
        <td><%= link_to 'Edit', edit_series_path(series) %></td>
        <td><%= link_to 'Destroy', series, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Series', new_series_path %>

app/views/series/show.html.erb
<p id="notice"><%= notice %></p>

<div>
  <strong>Title:</strong>
  <%= @series.title %>
</div>

<div>
  <strong>Genre:</strong>
  <%= @series.genre.title %>
</div>

<div>
  <b>Photo:</b>
  <% if @series.has_photo? %>
    <%= image_tag @series.photo_path %>
  <% else %>
    No photo.
  <% end %>
</div>

<%= link_to 'Add season', new_series_season_path(@series) %> |
<%= link_to 'Edit', edit_series_path(@series) %> |
<%= link_to 'Back', series_index_path %>